### ISSUE TITLE
Allow different border colors for different applications

### ISSUE THREAD

**Issue by raner** [FelixKratz/JankyBorders#124] opened 2024-10-02 03:40 UTC
I'm wondering what would be involved in supporting different border colors for different applications. This would solve my [long-standing problem](https://apple.stackexchange.com/questions/408620) of quickly distinguishing many similar looking application windows when using the exposé function.
Instead of having one border color for the active window and another color for all inactive windows, different border colors could be configured on a per-application basis (e.g., dark green for inactive console, bright green for active).
Since a lot of apps are web-based these days, it would also be helpful for some frequently used applications (e.g., Chrome) if borders could further be configured based on certain strings that occur in the title bar.

**Comment by Bellavene** [comment] 2024-10-07 21:39
duplicate of https://github.com/FelixKratz/JankyBorders/issues/57

**Closed** 2024-12-09 14:35 UTC
