### ISSUE TITLE
Safari: border disappears on link hover

### ISSUE THREAD

**Issue by kinglouie** [FelixKratz/JankyBorders#16] opened 2023-11-11 14:56 UTC
Just installed JankyBorders and noticed that the border around safari browser disappears as soon as I hover a link an a website. 
Maybe this is because safari creates some kind of window for displaying the link target url in the bottom left corner?

**Comment by FelixKratz** [comment] 2023-11-11 15:15
I see what the problem is. I think I have am idea how to fix it.

**Comment by FelixKratz** [comment] 2023-11-11 15:37
Should be fixed.

**Closed** 2023-11-11 15:40 UTC
Labels: available on master

**Comment by kinglouie** [comment] 2023-11-11 18:24
Nice that was really fast 😊
