### ISSUE TITLE
Border appear on wrong display

### ISSUE THREAD

**Issue by brorbw** [FelixKratz/JankyBorders#14] opened 2023-11-07 23:28 UTC
I have experienced that the border will appear on the "correct" window but on the wrong display. I have noticed that from time to time, the border will appear on the wrong display. 
Say I have two displays with two open windows each in a vertical split view. Display A, has A.l (left) and A.r (right) as windows, and display B, has B.l and B.r. Sometimes I experience that if B.l have focus A.l will have drawn border and vice versa.

**Comment by FelixKratz** [comment] 2023-11-08 05:59
So only the wrong window is highlighted, i.e. the window on the wrong display is marked as being active? Or is the border displaced in a strange way? If it is the first I have an idea how to fix it.

**Comment by FelixKratz** [comment] 2023-11-08 08:08
Altough I can not reproduce the issue, I believe this commit should fix it: https://github.com/FelixKratz/JankyBorders/commit/ff54f8e11e0a620fff145f170a54cde58db6deae

**Closed** 2023-11-08 09:20 UTC
Labels: bug, available on master

**Comment by albertsj1** [comment] 2023-11-08 21:52
@FelixKratz  I just wanted to say thank you for creating this and fixing this bug.  I know it's not supported, but I'm running this on Ventura 13.6.1 on a late 2019 Macbook Pro, and after this fix (and the others from today), it seems to be working flawlessly for me using Yabai with 3 external monitors and 1 of the monitors has 9 spaces.

**Comment by brorbw** [comment] 2023-11-08 23:26
Yes, that does indeed fix the issue! Thank you for the swift fix!
