### ISSUE TITLE
Repeated crash reports

### ISSUE THREAD

**Issue by ViaxCo** [FelixKratz/JankyBorders#94] opened 2024-05-04 04:02 UTC
Hello there! I've quite enjoyed my experience using this package, great work on this.

I've experienced about two crashes so far, but I'm not exactly what the causes are. I'm putting pastebin links to them so that I don't clutter this issue with logs:

[borders crash report 1](https://pastebin.com/eK2TLSKw)
[borders crash report 2](https://pastebin.com/WexXSLr2)

I am using `yabai` to start `borders` and this is my config:

```bash
borders active_color=0xFF03fc13 inactive_color=0x4D03fc13 width=5.0 hidpi=on &
```

**Comment by JakubAndrysek** [comment] 2024-05-04 15:52
Same for me. Borders crashed more than five times per day.
Running as brew service

```bash
#!/bin/bash

options=(
	style=round
	width=6.0
	hidpi=off
	active_color=0xff46ccff  # https://encycolorpedia.com/46ccff
	inactive_color=0xff414550 # https://encycolorpedia.com/414550
)

borders "${options[@]}"
```

[My crash report](https://pastebin.com/YdvY33x3)
After crash dialog the app is still running.

**Comment by Bellavene** [comment] 2024-05-11 22:01
> ```shell
> borders active_color=0xFF03fc13 inactive_color=0x4D03fc13 width=5.0 hidpi=on &
> ```

I don't have any crashes. Try this
`borders active_color=0xFF03fc13 inactive_color=0x4D03fc13 width=5.0 hidpi=on 2>/dev/null 1>&2 &`

**Comment by FelixKratz** [comment] 2024-05-16 16:39
Duplicate of #83. Lets track the problem there.

**Closed by FelixKratz** 2024-05-16 16:39 UTC
