### ISSUE TITLE
Bug: window outline with dark background left behind after window close

### ISSUE THREAD

**Issue by kfernandez31** [FelixKratz/JankyBorders#121] opened 2024-09-24 05:15 UTC
Hi,

When I work in CLion, I often open a bunch of small windows in it. I noticed that sometimes when one of them closes, its outline stays on the screen, like the small pane you see in my screenshot. I can only get rid of it if I do `brew restart services borders`. 

Before taking this screenshot, I also opened two projects in CLion in separate windows, then quit the app, and this too left behind a pane, this time as big as the entire, with my active border color.

I don't know if this issue relates only to CLion, but I don't recall experiencing it with any other app. Maybe that's because I don't typically work with apps that open small windows within them, I'm not sure.

![SCR-20240924-gvjc](https://github.com/user-attachments/assets/4d6c0a0f-bf12-43a2-ba1b-266a54280e61)

Thanks in advance for looking into this.

**Comment by Bellavene** [comment] 2024-10-07 21:31
duplicate of https://github.com/FelixKratz/JankyBorders/issues/111

**Closed** 2024-12-09 14:40 UTC
