### ISSUE TITLE
borders spontaneously change from a nice gradient to white

### ISSUE THREAD

**Issue by maddie-drake-ac** [FelixKratz/JankyBorders#86] opened 2024-04-17 04:41 UTC
Thank you for all your hard work on jankyborders and sketchybar! I'm having a small issue with borders tho.

I'm using borders invoked in my yabairc. Regularly I notice that the borders have turned to white from the nice gradient I have set up. Restarting yabai resolves this and since I realized that I haven't tried anything else. Be nice if it didn't happen tho.

Here's how I start borders in yabairc:
borders active_color="gradient(top_left=0xff571a74,bottom_right=0xffff0066)" inactive_color="gradient(top_right=0xff340F45,bottom_left=0xff7F002A)" width=8 hidpi=on &

(I only just now turned on the hidpi while I was reading the manpages for how I might restart borders only)
if you need more just let me know :)

Thanks
Maddie

**Comment by FelixKratz** [comment] 2024-04-27 10:12
I think this might be due to a crash of the borders process you started from yabai. Could you check "Console.app -> Crash Reports" for entries from `borders`?

**Comment by FelixKratz** [comment] 2024-05-16 16:39
Duplicate of #83

**Closed by FelixKratz** 2024-05-16 16:39 UTC
