### ISSUE TITLE
Issues with Yabai Focus Follows Mouse

### ISSUE THREAD

**Issue by 2mnml** [FelixKratz/JankyBorders#33] opened 2023-12-11 22:10 UTC
In my yabairc, i have the following:

yabai -m config focus_follows_mouse autofocus

So when I move my mouse onto a new window, it will focus that window. The border will not switch to that focused window unless I click on it after moving the mouse. 

Borders at the end of my yabairc:

borders active_color=0xffcba6f7 inactive_color=0xff1e1e2e width=5.0 &

See attached screenshot, the left window is where I had moved my mouse, and the right window is showing the border

<img width="1470" alt="Screenshot 2023-12-11 at 4 09 16 PM" src="https://github.com/FelixKratz/JankyBorders/assets/90079179/ed4b2da9-96a5-4de3-920a-883f147b6275">

**Comment by FelixKratz** [comment] 2023-12-11 22:12
Duplicate of #15

**Closed by FelixKratz** 2023-12-11 22:12 UTC
